CREATE TABLE MyWork (
    WorkID INT IDENTITY(1,1) PRIMARY KEY,
    StudentId NVARCHAR(50) NOT NULL,
    TaskName NVARCHAR(200) NOT NULL,
    FilePath NVARCHAR(500) NULL,
    WorkDate DATE NOT NULL
);
SELECT * FROM MFFSS.dbo.MyWork
TRUNCATE TABLE MyWork;
